# Generated by Django 5.1 on 2024-10-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Task Update', 'Task Update'), ('Project Update', 'Project Update'), ('Reminder', 'Reminder'), ('Custom Reminder', 'Custom Reminder'), ('Task Created', 'Task Created')], max_length=20),
        ),
    ]
