# Generated by Django 5.1 on 2024-10-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='custom_reminder_interval',
            field=models.IntegerField(default=24, help_text='Interval in hours for custom reminders'),
        ),
    ]
