<<<<<<< HEAD
# Generated by Django 5.1 on 2024-10-19 13:14
=======
# Generated by Django 5.1 on 2024-10-15 00:46
>>>>>>> 4390c64973c8e0b22f7e27ee8322a87ca9a1b232

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfile',
            name='file_uri',
            field=models.FileField(upload_to='task_files/', verbose_name='file_uri'),
        ),
    ]
