# Generated by Django 5.1 on 2024-10-22 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskfile_file_uri'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskComment',
        ),
    ]
