# Generated by Django 5.1 on 2024-10-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_remove_taskfile_task_task_task_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_file",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="files_tasks", to="task.taskfile"
            ),
        ),
    ]
