# Generated by Django 5.1 on 2024-10-22 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_alter_task_task_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="task_file",
        ),
    ]
